

# Config file for NEAT-CPPN system.

# Could do some of this as command_line options.
visible: True
evaluation: interactive # / target / imagenet
max_generations: 50

population_settings:
    size: 28
    mutation_rate: 0.5
    breed_method: selected # / total / species

image_settings:
    colour_channels: 3
    bias_length: 1
    fourier_features: 0

target_image: 'duck_bw_128.png'

genome_settings:
    activation_funcs:
        - sigmoid
        - relu
        - tanh
        - sin
        - abs
        - gaussian
        - mod
        - round
        - point
    output_funcs:
        - sigmoid
        - gaussian
    mutation_funcs:
        - {func: alter_wgt, prob: 0.4}
        - {func: flip_wgt, prob: 0.1}
        - {func: add_connection, prob: 0.3}
        - {func: add_node, prob: 0.1}
        - {func: disable_connection, prob: 0.1}
    disable_prob: 0.6

save_location: '/home/riversdale/Documents/MSc/thesis/rw_neat/output/'
save_size: 512

