

# Config file for NEAT-CPPN system.

# Could do some of this as command_line options.
interactive_mode: True

population_size: 28
colour_channels: 3
bias_length: 1
fourier_feautres: 0

mutation_types:
- {func: alter_wgt, prob: 0.4}
- {func: flip_wgt, prob: 0.1}
- {func: add_connection, prob: 0.3}
- {func: add_node, prob: 0.1}
- {func: disable_connection, prob: 0.1}

functions:
- sigmoid
- relu
- tanh
- sin
- abs
- gaussian
- mod
- round
- point

output_functions:
- sigmoid
- gaussian

