#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 22 20:58:33 2020

@author: riversdale
"""


# Trying to generate a fe simple illustrative genomes
from image_cppn import ImageCreator
from genome import Genome
import numpy as np

# nofunc, xcoords
G = Genome(4, 1, init_conns=False, output_funcs=['sigmoid'])
G._create_conn_gene(path=(0,4), wgt=2)
C = ImageCreator(colour_channels=1)
C.bias_vec = [1]
img = C.create_image(G)
img.show()

# abs, xcoords
G = Genome(4, 1, init_conns=False, output_funcs=['sigmoid'])
G._node_genes.append({
    'id': 5,
    'layer': 'hidden',
    'agg_func': 'sum',
    'act_func': 'abs',
    'act_args': {}
})
G._create_conn_gene(path=(0,5), wgt=1)
G._create_conn_gene(path=(3,4), wgt=-2) #bias
G._create_conn_gene(path=(5,4), wgt=3)
C = ImageCreator(colour_channels=1)
C.bias_vec = [1]
img = C.create_image(G)
img.show()

# round, dcoords
G = Genome(4, 1, init_conns=False, output_funcs=['sigmoid'])
G._node_genes.append({
    'id': 5,
    'layer': 'hidden',
    'agg_func': 'sum',
    'act_func': 'round',
    'act_args': {}
})
G._create_conn_gene(path=(2,5), wgt=0.5)
G._create_conn_gene(path=(3,5), wgt=-1) #bias
G._create_conn_gene(path=(5,4), wgt=3)
C = ImageCreator(colour_channels=1)
C.bias_vec = [1]
img = C.create_image(G)
img.show()

# sin, ycoors
G = Genome(4, 1, init_conns=False, output_funcs=['sigmoid'])
G._node_genes.append({
    'id': 5,
    'layer': 'hidden',
    'agg_func': 'sum',
    'act_func': 'sin',
    'act_args': {}
})
G._create_conn_gene(path=(1,5), wgt=10)
G._create_conn_gene(path=(3,5), wgt=1) #bias
G._create_conn_gene(path=(5,4), wgt=1.5)
C = ImageCreator(colour_channels=1)
C.bias_vec = [1]
img = C.create_image(G)
img.show()

# relu, xcoords
G = Genome(4, 1, init_conns=False, output_funcs=['sigmoid'])
G._node_genes.append({
    'id': 5,
    'layer': 'hidden',
    'agg_func': 'sum',
    'act_func': 'relu',
    'act_args': {}
})
G._create_conn_gene(path=(0,5), wgt=3)
G._create_conn_gene(path=(3,4), wgt=-2) #bias
G._create_conn_gene(path=(5,4), wgt=1)
C = ImageCreator(colour_channels=1)
C.bias_vec = [1]
img = C.create_image(G)
img.show()

# mod, xcoords+ycoords
G = Genome(4, 1, init_conns=False, output_funcs=['sigmoid'])
G._node_genes.append({
    'id': 5,
    'layer': 'hidden',
    'agg_func': 'sum',
    'act_func': 'mod',
    'act_args': {}
})
G._create_conn_gene(path=(0,5), wgt=4)
G._create_conn_gene(path=(1,5), wgt=4)
G._create_conn_gene(path=(3,4), wgt=-1) #bias
G._create_conn_gene(path=(5,4), wgt=1)
C = ImageCreator(colour_channels=1)
C.bias_vec = [1]
img = C.create_image(G)
img.show()

# point, xcoords
G = Genome(4, 1, init_conns=False, output_funcs=['sigmoid'])
G._node_genes.append({
    'id': 5,
    'layer': 'hidden',
    'agg_func': 'sum',
    'act_func': 'point',
    'act_args': {'p': 0.8}
})
G._create_conn_gene(path=(0,5), wgt=0)
G._create_conn_gene(path=(1,5), wgt=0)
G._create_conn_gene(path=(2,5), wgt=1)
G._create_conn_gene(path=(3,5), wgt=-0.5) #bias
G._create_conn_gene(path=(5,4), wgt=1)
C = ImageCreator(colour_channels=1)
C.bias_vec = [1]
img = C.create_image(G)
img.show()