# Config file for CPPN-NEAT system.

visible: True # whether to show to UI
evaluation: interactive # [/ target / imagenet] # which evaluator to use
max_generations: 50 # program will terminate terminate after this many generations

population_settings:
    size: 28
    mutation_rate: 0.6
    breed_method:  selected # [/ total]

image_settings:
    colour_channels: 3 # 3 for RGB, 1 for grayscale
    coord_types: [x, y, r] # any combination of x & y for Cartesian, r and phi for Polar, perlin for noise
    bias_length: 1
    fourier_features: 0 # set to >0 (eg. 64) to use Fourier feauture mapping

target_image: 'duck_bw_128.png' # only relevant if using the 'target' evaluator

# Section below sets the probability that each activation/aggregation/output function and mutation type will be selected.
genome_settings:
    activation_funcs:
        - {func: sigmoid, prob: 1}
        - {func: relu, prob: 1}
        - {func: tanh, prob: 1}
        - {func: sin, prob: 1}
        - {func: abs, prob: 1}
        - {func: mod, prob: 1}
        - {func: round, prob: 1}
        - {func: point, prob: 1}
        - {func: nofunc, prob: 0.5}
        - {func: gaussian_white, prob: 0}
        - {func: gaussian_black, prob: 0}
    aggregation_funcs:
        - {func: sum, prob: 0.8}
        - {func: max, prob: 0.2} # gives sharp angles
    output_funcs:
        - {func: sigmoid, prob: 0.8} # more pastel
        - {func: gaussian_black, prob: 0.1} # neon with black background
        - {func: gaussian_white, prob: 0.1} # neon with white background
    mutation_funcs:
        - {func: alter_wgt, prob: 0.4}
        - {func: flip_wgt, prob: 0.1}
        - {func: add_connection, prob: 0.3}
        - {func: add_node, prob: 0.1}
        - {func: disable_connection, prob: 0.1}
    disable_prob: 0.6

save_location: './output' # saved images & genomes will appear in this folder.
save_size: 512 # resolution for saved images

